language: objective-c

env:
 global:
  - EnableNuGetPackageRestore=true
 matrix:
  - MONO_VERSION="3.6.0.39"
before_install:
 - wget "http://download.mono-project.com/archive/3.6.0/macos-10-x86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
 - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /

script:
 - xbuild Metrics.Sln /p:Configuration="MonoDebug"
 - xbuild Metrics.Sln /p:Configuration="MonoRelease"
 - mono .nuget/NuGet.exe restore Metrics.sln 
 - mono ./packages/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./bin/MonoRelease/Tests/Metrics.Tests.dll